# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recording.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from first import Ui_Form_3
from second import Ui_Form_4
from third import Ui_Form_5
from fourth import Ui_Form_6
from edit import Ui_Form_7

class Ui_Form_2(object):
    def openWindow4(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Form_3()
        self.ui.setupUi(self.window)
        self.window.show()
    def openWindow5(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Form_4()
        self.ui.setupUi(self.window)
        self.window.show()
    def openWindow6(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Form_5()
        self.ui.setupUi(self.window)
        self.window.show()
    def openWindow7(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Form_6()
        self.ui.setupUi(self.window)
        self.window.show()
    def openWindow8(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Form_7()
        self.ui.setupUi(self.window)
        self.window.show()



    def setupUi(self, Form_2):
        Form_2.setObjectName("Form_2")
        Form_2.resize(1108, 818)
        self.pushButton_6 = QtWidgets.QPushButton(Form_2,clicked = lambda: self.openWindow4())
        self.pushButton_6.setGeometry(QtCore.QRect(870, 280, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.pushButton_6.setDefault(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form_2,clicked = lambda: self.openWindow5())
        self.pushButton_7.setGeometry(QtCore.QRect(140, 290, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.pushButton_7.setDefault(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form_2,clicked = lambda: self.openWindow6())
        self.pushButton_8.setGeometry(QtCore.QRect(870, 510, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.pushButton_8.setDefault(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form_2,clicked = lambda: self.openWindow7())
        self.pushButton_9.setGeometry(QtCore.QRect(140, 510, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.pushButton_9.setDefault(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form_2,clicked = lambda: self.openWindow8())
        self.pushButton_10.setGeometry(QtCore.QRect(450, 690, 231, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.pushButton_10.setDefault(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_1 = QtWidgets.QLabel(Form_2)
        self.label_1.setGeometry(QtCore.QRect(-130, 70, 851, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("Color: rgba(0, 83, 139, 1)\n"
"")
        self.label_1.setObjectName("label_1")

        self.retranslateUi(Form_2)
        QtCore.QMetaObject.connectSlotsByName(Form_2)

    def retranslateUi(self, Form_2):
        _translate = QtCore.QCoreApplication.translate
        Form_2.setWindowTitle(_translate("Form_2", "Form"))
        self.pushButton_6.setText(_translate("Form_2", "الرغبة الاولي"))
        self.pushButton_7.setText(_translate("Form_2", "الرغبة الثانية"))
        self.pushButton_8.setText(_translate("Form_2", "الرغبة الثالثة"))
        self.pushButton_9.setText(_translate("Form_2", "الرغبة الرابعة"))
        self.pushButton_10.setText(_translate("Form_2", "تعديل البيانات"))
        self.label_1.setText(_translate("Form_2", "نافذة الرغبات "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_2 = QtWidgets.QWidget()
    ui = Ui_Form_2()
    ui.setupUi(Form_2)
    Form_2.show()
    sys.exit(app.exec_())
