# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_4(object):
    def setupUi(self, Form_4):
        Form_4.setObjectName("Form_4")
        Form_4.resize(1096, 831)
        self.pushButton_17 = QtWidgets.QPushButton(Form_4)
        self.pushButton_17.setGeometry(QtCore.QRect(740, 630, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.pushButton_17.setDefault(True)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(Form_4)
        self.pushButton_18.setGeometry(QtCore.QRect(70, 640, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.pushButton_18.setDefault(True)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_16 = QtWidgets.QPushButton(Form_4)
        self.pushButton_16.setGeometry(QtCore.QRect(60, 440, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.pushButton_16.setDefault(True)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_15 = QtWidgets.QPushButton(Form_4)
        self.pushButton_15.setGeometry(QtCore.QRect(740, 440, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.pushButton_15.setDefault(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_1 = QtWidgets.QLabel(Form_4)
        self.label_1.setGeometry(QtCore.QRect(-90, 30, 851, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("Color: rgba(0, 83, 139, 1)\n"
"")
        self.label_1.setObjectName("label_1")
        self.label = QtWidgets.QLabel(Form_4)
        self.label.setGeometry(QtCore.QRect(770, 560, 141, 31))
        self.label.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form_4)
        self.label_2.setGeometry(QtCore.QRect(70, 570, 141, 31))
        self.label_2.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form_4)
        self.label_3.setGeometry(QtCore.QRect(90, 760, 141, 31))
        self.label_3.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form_4)
        self.label_4.setGeometry(QtCore.QRect(770, 750, 141, 31))
        self.label_4.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.label_4.setObjectName("label_4")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(270, 140, 641, 41))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(270, 190, 641, 41))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form_4)
        self.lineEdit_9.setGeometry(QtCore.QRect(270, 240, 641, 41))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(270, 290, 641, 41))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(Form_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(270, 340, 641, 41))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form_4)
        self.lineEdit_12.setGeometry(QtCore.QRect(270, 390, 641, 41))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_8 = QtWidgets.QLabel(Form_4)
        self.label_8.setGeometry(QtCore.QRect(100, 130, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("Color: rgba(0, 135, 141, 1)\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(Form_4)
        self.label_7.setGeometry(QtCore.QRect(100, 180, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("Color: rgba(0, 135, 141, 1)\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(Form_4)
        self.label_5.setGeometry(QtCore.QRect(100, 240, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("Color: rgba(0, 135, 141, 1)\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form_4)
        self.label_6.setGeometry(QtCore.QRect(100, 290, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("Color: rgba(0, 135, 141, 1)\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(Form_4)
        self.label_9.setGeometry(QtCore.QRect(110, 340, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("Color: rgba(0, 135, 141, 1)\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form_4)
        self.label_10.setGeometry(QtCore.QRect(110, 390, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("Color: rgba(0, 135, 141, 1)\n"
"")
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Form_4)
        QtCore.QMetaObject.connectSlotsByName(Form_4)

    def retranslateUi(self, Form_4):
        _translate = QtCore.QCoreApplication.translate
        Form_4.setWindowTitle(_translate("Form_4", "Form"))
        self.pushButton_17.setText(_translate("Form_4", "IT"))
        self.pushButton_18.setText(_translate("Form_4", "IS"))
        self.pushButton_16.setText(_translate("Form_4", "CS"))
        self.pushButton_15.setText(_translate("Form_4", "SE"))
        self.label_1.setText(_translate("Form_4", "الرغبة الثانية"))
        self.label.setText(_translate("Form_4", "<html><head/><body><p><span style=\" font-size:18pt;\">TextLabel</span></p></body></html>"))
        self.label_2.setText(_translate("Form_4", "<html><head/><body><p><span style=\" font-size:18pt;\">TextLabel</span></p></body></html>"))
        self.label_3.setText(_translate("Form_4", "<html><head/><body><p><span style=\" font-size:18pt;\">TextLabel</span></p></body></html>"))
        self.label_4.setText(_translate("Form_4", "<html><head/><body><p><span style=\" font-size:18pt;\">TextLabel</span></p></body></html>"))
        self.label_8.setText(_translate("Form_4", "name"))
        self.label_7.setText(_translate("Form_4", "email"))
        self.label_5.setText(_translate("Form_4", "address"))
        self.label_6.setText(_translate("Form_4", "phone"))
        self.label_9.setText(_translate("Form_4", "age"))
        self.label_10.setText(_translate("Form_4", "GPA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_4 = QtWidgets.QWidget()
    ui = Ui_Form_4()
    ui.setupUi(Form_4)
    Form_4.show()
    sys.exit(app.exec_())
