# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_9(object):
    def setupUi(self, Form_9):
        Form_9.setObjectName("Form_9")
        Form_9.resize(961, 1028)
        self.label_1 = QtWidgets.QLabel(Form_9)
        self.label_1.setGeometry(QtCore.QRect(-250, 0, 851, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("Color: rgba(0, 83, 139, 1)\n"
"")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Form_9)
        self.label_2.setGeometry(QtCore.QRect(540, 130, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("Color: rgba(0, 83, 139, 1)\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form_9)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("Color: rgba(0, 83, 139, 1)\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form_9)
        self.label_4.setGeometry(QtCore.QRect(560, 540, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("Color: rgba(0, 83, 139, 1)\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form_9)
        self.label_5.setGeometry(QtCore.QRect(40, 540, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("Color: rgba(0, 83, 139, 1)\n"
"")
        self.label_5.setObjectName("label_5")
        self.tableWidget = QtWidgets.QTableWidget(Form_9)
        self.tableWidget.setGeometry(QtCore.QRect(510, 200, 411, 321))
        self.tableWidget.setRowCount(8)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget_2 = QtWidgets.QTableWidget(Form_9)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 200, 411, 321))
        self.tableWidget_2.setRowCount(8)
        self.tableWidget_2.setColumnCount(8)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_3 = QtWidgets.QTableWidget(Form_9)
        self.tableWidget_3.setGeometry(QtCore.QRect(500, 620, 451, 321))
        self.tableWidget_3.setRowCount(8)
        self.tableWidget_3.setColumnCount(8)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_4 = QtWidgets.QTableWidget(Form_9)
        self.tableWidget_4.setGeometry(QtCore.QRect(20, 620, 411, 321))
        self.tableWidget_4.setRowCount(8)
        self.tableWidget_4.setColumnCount(8)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.pushButton_27 = QtWidgets.QPushButton(Form_9)
        self.pushButton_27.setGeometry(QtCore.QRect(740, 530, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(Form_9)
        self.pushButton_28.setGeometry(QtCore.QRect(250, 540, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_30 = QtWidgets.QPushButton(Form_9)
        self.pushButton_30.setGeometry(QtCore.QRect(250, 950, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_29 = QtWidgets.QPushButton(Form_9)
        self.pushButton_29.setGeometry(QtCore.QRect(770, 950, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName("pushButton_29")

        self.retranslateUi(Form_9)
        QtCore.QMetaObject.connectSlotsByName(Form_9)

    def retranslateUi(self, Form_9):
        _translate = QtCore.QCoreApplication.translate
        Form_9.setWindowTitle(_translate("Form_9", "Form"))
        self.label_1.setText(_translate("Form_9", "عرض النتائج"))
        self.label_2.setText(_translate("Form_9", "CS"))
        self.label_3.setText(_translate("Form_9", "SE"))
        self.label_4.setText(_translate("Form_9", "IT"))
        self.label_5.setText(_translate("Form_9", "IS"))
        self.pushButton_27.setText(_translate("Form_9", "عرض "))
        self.pushButton_28.setText(_translate("Form_9", "عرض "))
        self.pushButton_30.setText(_translate("Form_9", "عرض "))
        self.pushButton_29.setText(_translate("Form_9", "عرض "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_9 = QtWidgets.QWidget()
    ui = Ui_Form_9()
    ui.setupUi(Form_9)
    Form_9.show()
    sys.exit(app.exec_())
