# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'third.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_5(object):
    def setupUi(self, Form_5):
        Form_5.setObjectName("Form_5")
        Form_5.resize(1096, 831)
        self.pushButton_21 = QtWidgets.QPushButton(Form_5)
        self.pushButton_21.setGeometry(QtCore.QRect(740, 630, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.pushButton_21.setDefault(True)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(Form_5)
        self.pushButton_22.setGeometry(QtCore.QRect(70, 640, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.pushButton_22.setDefault(True)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_20 = QtWidgets.QPushButton(Form_5)
        self.pushButton_20.setGeometry(QtCore.QRect(60, 440, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.pushButton_20.setDefault(True)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_19 = QtWidgets.QPushButton(Form_5)
        self.pushButton_19.setGeometry(QtCore.QRect(740, 440, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.pushButton_19.setDefault(True)
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_1 = QtWidgets.QLabel(Form_5)
        self.label_1.setGeometry(QtCore.QRect(-90, 30, 851, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("Color: rgba(0, 83, 139, 1)\n"
"")
        self.label_1.setObjectName("label_1")
        self.label = QtWidgets.QLabel(Form_5)
        self.label.setGeometry(QtCore.QRect(770, 560, 141, 31))
        self.label.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form_5)
        self.label_2.setGeometry(QtCore.QRect(70, 570, 141, 31))
        self.label_2.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form_5)
        self.label_3.setGeometry(QtCore.QRect(90, 760, 141, 31))
        self.label_3.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form_5)
        self.label_4.setGeometry(QtCore.QRect(770, 750, 141, 31))
        self.label_4.setStyleSheet("Color: rgba(0, 7, 141, 1)\n"
"")
        self.label_4.setObjectName("label_4")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form_5)
        self.lineEdit_13.setGeometry(QtCore.QRect(270, 140, 641, 41))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(Form_5)
        self.lineEdit_14.setGeometry(QtCore.QRect(270, 190, 641, 41))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(Form_5)
        self.lineEdit_15.setGeometry(QtCore.QRect(270, 240, 641, 41))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(Form_5)
        self.lineEdit_16.setGeometry(QtCore.QRect(270, 290, 641, 41))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(Form_5)
        self.lineEdit_17.setGeometry(QtCore.QRect(270, 340, 641, 41))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(Form_5)
        self.lineEdit_18.setGeometry(QtCore.QRect(270, 390, 641, 41))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_8 = QtWidgets.QLabel(Form_5)
        self.label_8.setGeometry(QtCore.QRect(100, 130, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("Color: rgba(0, 135, 141, 1)\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(Form_5)
        self.label_7.setGeometry(QtCore.QRect(100, 180, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("Color: rgba(0, 135, 141, 1)\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(Form_5)
        self.label_5.setGeometry(QtCore.QRect(100, 240, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("Color: rgba(0, 135, 141, 1)\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form_5)
        self.label_6.setGeometry(QtCore.QRect(100, 290, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("Color: rgba(0, 135, 141, 1)\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(Form_5)
        self.label_9.setGeometry(QtCore.QRect(110, 340, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("Color: rgba(0, 135, 141, 1)\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form_5)
        self.label_10.setGeometry(QtCore.QRect(110, 390, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("Color: rgba(0, 135, 141, 1)\n"
"")
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Form_5)
        QtCore.QMetaObject.connectSlotsByName(Form_5)

    def retranslateUi(self, Form_5):
        _translate = QtCore.QCoreApplication.translate
        Form_5.setWindowTitle(_translate("Form_5", "Form"))
        self.pushButton_21.setText(_translate("Form_5", "IT"))
        self.pushButton_22.setText(_translate("Form_5", "IS"))
        self.pushButton_20.setText(_translate("Form_5", "CS"))
        self.pushButton_19.setText(_translate("Form_5", "SE"))
        self.label_1.setText(_translate("Form_5", "الرغبة الثالثة"))
        self.label.setText(_translate("Form_5", "<html><head/><body><p><span style=\" font-size:18pt;\">TextLabel</span></p></body></html>"))
        self.label_2.setText(_translate("Form_5", "<html><head/><body><p><span style=\" font-size:18pt;\">TextLabel</span></p></body></html>"))
        self.label_3.setText(_translate("Form_5", "<html><head/><body><p><span style=\" font-size:18pt;\">TextLabel</span></p></body></html>"))
        self.label_4.setText(_translate("Form_5", "<html><head/><body><p><span style=\" font-size:18pt;\">TextLabel</span></p></body></html>"))
        self.label_8.setText(_translate("Form_5", "name"))
        self.label_7.setText(_translate("Form_5", "email"))
        self.label_5.setText(_translate("Form_5", "address"))
        self.label_6.setText(_translate("Form_5", "phone"))
        self.label_9.setText(_translate("Form_5", "age"))
        self.label_10.setText(_translate("Form_5", "GPA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_5 = QtWidgets.QWidget()
    ui = Ui_Form_5()
    ui.setupUi(Form_5)
    Form_5.show()
    sys.exit(app.exec_())
